### ISSUE TITLE
Citation number not always returned by API

### ISSUE THREAD

**Issue by mheadd** [mheadd/albany-ticket-finder#1]
There seems to be a weird issue with the citation number not being returned for some records from the Socrata API for [this dataset](https://data.albanyny.gov/City-Finances/Outstanding-Parking-Tickets-04-1-16/474r-rd62), even though it is displayed when looking at the dataset in the portal, and when the citation number appears to be valid.

![citation-number-example](https://cloud.githubusercontent.com/assets/58419/14607108/363926c0-054e-11e6-8a30-edc5bcd34080.png)

Accessing the API like this:

``` bash
~$ https://data.albanyny.gov/resource/474r-rd62.json?license_plate_number=J478xA
```

Returns (missing `citation` field):

``` json
[
  {
    "remaining_balance": "65.00",
    "citation_amount": "40.00",
    "fees_fines": "25.00",
    "first_name": "ERIN",
    "license_plate_number": "J478XA",
    "middle_name": "T",
    "state_of_plate": "NY",
    "last_name": "WATERHOUSE",
    "issue_date": "2016-03-07T00:00:00"
  }
]
```

When the citation number is entered into the City of Albany online payment site, it appears to be valid:

![valid-citation-number](https://cloud.githubusercontent.com/assets/58419/14607234/b11c1ad2-054e-11e6-8d88-1f59a7e71108.png)

**Comment by marks** [comment]
Hey Mark - this has to do with the fact that the data publisher set the `citation` column to be a `Number` column and so while we show the non-compliant ID in the UI, it is not shown in the API. I would suggest reaching out to the dataset publisher and suggest they change the column to be a `Plain Text` column (if they expect to have text in there).

Let me know if there's anything else I can do to help!

**Comment by mheadd** [comment]
Ah, thanks @marks. I assume that is why it is italicized in the display..?

Will reach out to them and have them modify, Thanks!

**Comment by marks** [comment]
Yup, no problem! You can point them to the support article at https://support.socrata.com/hc/en-us/articles/202949918-Importing-Data-Types-and-You- ... specifically this paragraph. Of course, they can always contact support@socrata.com too

> It is important to note that if you have string values, e.g. text, in a number, money or percent field, these values will be greyed out and italicized. This is how the Socrata platform tells you that these values are invalid. If a dataset contains invalid values such as strings in a number, money or percent field, these will not export.

PS - nice work on this!

**Comment by mheadd** [comment]
New dataset published with proper type on `citation` column.

https://data.albanyny.gov/City-Finances/Outstanding-Parking-Tickets-04-18-16/bcev-vdhz
